{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
 name: {{ include "deploy-component.fullname" $ }}
  labels:
    {{- include "deploy-component.labels" . | nindent 4 }}
spec:
 storageClassName: {{ .Values.persistence.storageClass }}
 volumeMode: {{ .Values.persistence.volumeMode }}
 accessModes:
   - {{ .Values.persistence.accessMode | quote }}
 resources:
   requests:
     storage: {{ .Values.persistence.size | quote }}
 {{- end }}

 apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-apps-pvc
  namespace: postgres
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/namespace: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: postgres-storage
  volumeMode: Filesystem