apiVersion: v1
kind: Secret
metadata:
  name: {{ include "isbe-poc-middleware-managements.fullname" . }}
  labels:
    {{- include "isbe-poc-middleware-managements.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
    {{ $key }}: {{ $value | b64enc }}
  {{- end }}